# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-10 00:01
from __future__ import unicode_literals

import django.contrib.sites.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0023_merge'),
    ]

    operations = [
        #migrations.AlterModelManagers(
        #    name='layer',
        #    managers=[
        #        ('objects', django.contrib.sites.managers.CurrentSiteManager(b'site')),
        #    ],
        #),
        #migrations.AlterModelManagers(
        #    name='theme',
        #    managers=[
        #        ('objects', django.contrib.sites.managers.CurrentSiteManager(b'site')),
        #    ],
        #),
    ]
