# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-12 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0024_auto_20190510_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='show_legend',
            field=models.BooleanField(default=True, help_text=b'show the legend for this layer if available'),
        ),
    ]
