# Generated by Django 2.2.7 on 2019-11-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0032_auto_20191113_0013'),
    ]

    # This content moved to migration 0025 to facilitate merging in mida data
    operations = []
